# Generated by Django 3.2.7 on 2022-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真4'),
        ),
    ]
